### PR TITLE
Updates directory structure and files for Read The Docs

### LINKED ISSUE #39: FAQs question on AIDE Admin and update
From the review of the training docs on 10th Jan.
@heyhaleema 
Update documentation and question:
- [ ] Check on **FAQs** - Qu: If you don't know your AIDE Admin contact (currently states help is via AD jira desk) - Change to a placeholder "Local Trust AIDE platform owner (Information Asset Owner at Trust) via AIDE admin"
- [ ] Also need confirmation on whether AD would get updated if AIDE admin changes at a Trust and by who (do we need this in ongoing commitments for Trusts - keep AIC and or AD updated of changes to personnel) - would this be managed by AIC (Haleema mentioned management of an AIDE Admin user group by AIC so this needs confirming)?

### LINKED ISSUE #40: Change - Clinical Workflow is getting moved
@JoeBatt1989 Mentioned that 

- [ ] **Clincial Workflow** is getting moved (sorry don't think I captured the full details of where moving to, but hopefully this will be enough of a prompt!)

### LINKED ISSUE #42: Structure of .MD files
Hi @heyhaleema, @JoeBatt1989, @JillJarvis,

JupiterBook takes the first title of the .MD file and uses it as its title for the table of content in the site, for this reason, the title of each .MD file should be the first item of the file rather than how they are structured now with "table of content" as first line of the file

### LINKED ISSUE #44: Check AIDE docs website doesn't break when editing the repo
Hi @JoeBatt1989, @heyhaleema, @JillJarvis , there is a GitHub action that ensures the AIDE docs website updates automatically when you edit the repo. I have notices many docs have been added and approved to the repo but they have now "broken" the structure of the website as jupyterbook wants the folders and files structured in a particular way. 

I will now work on re-structuring the repo, but we all need to be aware of how the structure of added file should look like so that I don't need to continuosly re-do the same tasks to mantain the repo.

To this regard I suggest to read how the jupyterbook should be structured https://jupyterbook.org/en/stable/start/create.html include me as reviewer of PRs before merging.

### PR DESCRIPTION
**Pull request by heyhaleema**
This PR:

- Refactors directory structure to better organise content structure e.g., sections, pages, assets, etc. (resolves #40)
- Adds Read The Docs (RTD) setup (see RTD project page [here](https://readthedocs.org/projects/ai4vbh-aide/) and RTD webpage [here](https://ai4vbh-aide.readthedocs.io/en/latest/) (resolves #44)
- Refactors Markdown files to reStructuredText (RST) files (resolves #42 and #12)
- Makes minor edits to content (resolves #39, #36, and #35)
- Updates `requirements.txt` to include Read The Docs dependencies
- Updates and consolidates content e.g., documentation template, adds FLIP and AIDE roles Word document content to RST file, etc.
- Fixes typo in GH action filename

> ⚠️  To test the build of the Read The Docs page:
> 1. `git clone` this repo 
> 2. `git checkout` this branch
> 3. Run `pip install -r requirements.txt`
> 4. `cd` into the `docs/source/` directory
> 5. Run `make html`
> 6. Open the ``docs/build/index.html`` file in your browser

@Lucrezia-Cester Since Jupyter Book is unable to support separate documentation by version, I propose we go ahead with the Read The Docs changes and remove the Jupyter Book `_config.yml`, `_toc.yml`, and GH actions. If you're okay with this, I can delete these as part of this PR's commits.

### CODE REVIEW

**Review by Lucrezia-Cester — COMMENTED** [review]
Hi @heyhaleema, could you please add these file titles to the .toc.yml file?

**Comment by heyhaleema** [comment]
@Lucrezia-Cester In addition to the changes I've now made to `_toc.yml` (based on [this](https://jupyterbook.org/en/stable/structure/toc.html#use-parts-to-organize-chapters) section) and `_config.yml`, I've made some edits to the GH Actions to reflect the new directory structure.

Assuming the above works/hasn't broken anything, I think we should have a step in the GH Action to [generate the `_toc.yml`](https://jupyterbook.org/en/stable/structure/toc.html#use-parts-to-organize-chapters) based on our repo structure (i.e., make more changes in this PR before merging) - what do you think?

**Comment by Lucrezia-Cester** [comment]
@heyhaleema I think the current GitHub action is good enough as we will always need to manually input toc titles

**Comment by Lucrezia-Cester** [comment]
@heyhaleema have you checked what it looks like once compiled from the terminal?

**Comment by Lucrezia-Cester** [comment]
Hi @heyhaleema, yes please do remove the jupiterbook references

**Comment by heyhaleema** [comment]
> Hi @heyhaleema, yes please do remove the jupiterbook references

@Lucrezia-Cester Done! ✔️

**Pull request merged**
